### ISSUE TITLE
1.1. Startup Profile

### ISSUE THREAD

**Issue by coffeeisknowledge** [AppsWeb-DeltaTech-SW57/Informe-de-proyecto#1]
1.1.1. Descripción de la Startup
1.1.2. Perfiles de integrantes del equipo

**Comment by JulioElsnerDLTU** [comment]
Abel y yo realizamos la finalización de los puntos 1.1.1. Descripción de la Startup & 1.1.2. Perfiles de integrantes del equipo en Mark Down.
Adjunto las pruebas: 

1.1.1.
![Image](https://github.com/AppsWeb-DeltaTech-SW57/Informe-de-proyecto/assets/111522511/30c490df-b631-44cf-9008-08f2f0bd669e)

1.1.2.
![Image](https://github.com/AppsWeb-DeltaTech-SW57/Informe-de-proyecto/assets/111522511/0fe6b5a3-6186-417c-96d1-ef9a40c84669)
