### ISSUE TITLE
1.2. Solution Profile

### ISSUE THREAD

**Issue by coffeeisknowledge** [AppsWeb-DeltaTech-SW57/Informe-de-proyecto#2]
1.2.1 Antecedentes y problemática
1.2.2 Lean UX Process.
1.2.2.1. Lean UX Problem Statements.
1.2.2.2. Lean UX Assumptions.
1.2.2.3. Lean UX Hypothesis Statements.
1.2.2.4. Lean UX Canvas.

**Comment by JulioElsnerDLTU** [comment]
Abel y yo realizamos la finalización de los puntos mencionados posteriormente en Mark Down.
Adjunto las pruebas:

1.2.1 Antecedentes y problemática
![Image](https://github.com/AppsWeb-DeltaTech-SW57/Informe-de-proyecto/assets/111522511/1668a5ff-8cdd-4972-8237-3356c449d5aa)

![Image](https://github.com/AppsWeb-DeltaTech-SW57/Informe-de-proyecto/assets/111522511/045693ab-cfbc-4d0f-af7c-e1d27d754e82)

1.2.2 Lean UX Process.
![Image](https://github.com/AppsWeb-DeltaTech-SW57/Informe-de-proyecto/assets/111522511/431ebaf5-4563-4311-92b3-a3aec12f0d51)

1.2.2.1. Lean UX Problem Statements.
![Image](https://github.com/AppsWeb-DeltaTech-SW57/Informe-de-proyecto/assets/111522511/1952b5cb-a4e8-4559-8020-a70a85d1d459)

1.2.2.2. Lean UX Assumptions.
![Image](https://github.com/AppsWeb-DeltaTech-SW57/Informe-de-proyecto/assets/111522511/c4f82cc0-e5da-4ba6-a602-81effb8e877f)

![Image](https://github.com/AppsWeb-DeltaTech-SW57/Informe-de-proyecto/assets/111522511/c9bfd1dc-c5b2-45bc-80d5-fe9f8d2f1379)

![Image](https://github.com/AppsWeb-DeltaTech-SW57/Informe-de-proyecto/assets/111522511/ffb807df-684b-4531-839d-9a14bd1379f6)

![Image](https://github.com/AppsWeb-DeltaTech-SW57/Informe-de-proyecto/assets/111522511/70cfd388-301a-4f8a-9f06-7255be665b91)

![Image](https://github.com/AppsWeb-DeltaTech-SW57/Informe-de-proyecto/assets/111522511/09bd5610-4816-41d5-9ab8-e487ab7f2df6)

![Image](https://github.com/AppsWeb-DeltaTech-SW57/Informe-de-proyecto/assets/111522511/ee485a1f-1269-452c-a5c4-7431d2ce5b7c)

![Image](https://github.com/AppsWeb-DeltaTech-SW57/Informe-de-proyecto/assets/111522511/44618aef-5eb1-46b6-b911-c81156c4cf0b)

1.2.2.3. Lean UX Hypothesis Statements.
![Image](https://github.com/AppsWeb-DeltaTech-SW57/Informe-de-proyecto/assets/111522511/c696d069-7e9c-495c-a4c4-0328459886ef)

1.2.2.4. Lean UX Canvas.
![Image](https://github.com/AppsWeb-DeltaTech-SW57/Informe-de-proyecto/assets/111522511/2fb2ca40-f900-41b7-a949-8f48fc32616a)
 |
 |
V
![Image](https://github.com/AppsWeb-DeltaTech-SW57/Informe-de-proyecto/assets/111522511/34ef33ed-7f32-497e-bd8e-1ce44f7926bd)
