### ISSUE TITLE
1.3. Segmentos Objetivos

### ISSUE THREAD

**Issue by coffeeisknowledge** [AppsWeb-DeltaTech-SW57/Informe-de-proyecto#3]
Actividad grupal para debatir sobre los segmentos finales de nuestra web application.

**Comment by JulioElsnerDLTU** [comment]
Mediante una reunión estratégica con todo nuestro equipo, hemos tomado la decisión de identificar los dos segmentos objetivos para los cuales nuestra aplicación adquirirá un propósito definido.
Adjunto Pruebas:


**Segmento Objetivo N°1:**

![Image](https://github.com/AppsWeb-DeltaTech-SW57/Informe-de-proyecto/assets/111522511/e4b7e697-1278-4381-9bd9-2cee19fafdc6)

**Segmento Objetivo N°2:**

![Image](https://github.com/AppsWeb-DeltaTech-SW57/Informe-de-proyecto/assets/111522511/73ea4178-5442-43e1-93d6-29c9dded014e)
